version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm install -g firebase-tools
      - run: firebase deploy --token $FIREBASE_TOKEN

workflows:
  build-and-test:
    jobs:
      - build-and-test
